baseURL = "https://blog.bitchigo.icu/public"
title = "bitchigo's blog"
theme = "m10c"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
buildFuture = true
[params]
    author = "bitchigo"
    keywords = "HTML, java, js, spring, web"
    description = "一点一点的积累"
    subtitle = "简单记录一下"
[[params.social]]
  name = "github"
  url = "https://github.com/bitchigo"
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/bitchigo996"
[[menu.main]]           
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "类别"
  weight = 40
  identifier = "categories"
  url = "/categories/"